# Generated by Django 3.2.3 on 2021-05-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='prenume',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
