# Generated by Django 3.2.3 on 2021-05-22 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curs', '0003_auto_20210522_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('nume',)},
        ),
    ]
