# Generated by Django 3.2.3 on 2021-05-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curs', '0004_alter_student_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='prenume',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
