# Generated by Django 3.2.3 on 2021-05-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curs', '0007_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='cursuri',
            field=models.ManyToManyField(to='curs.Curs'),
        ),
    ]
