# Generated by Django 3.2.3 on 2021-05-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curs', '0008_auto_20210529_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='an',
            field=models.IntegerField(default=1),
        ),
    ]
