# Generated by Django 3.2.3 on 2021-06-05 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curs', '0009_student_an'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('nume', 'prenume')},
        ),
    ]
