# Generated by Django 3.2.4 on 2021-06-26 08:56

from django.db import migrations

def forward(apps, models):
    print("inainte")
    Student = apps.get_model('curs', 'Student')
    Student.objects.update(an=1)
    # for student in Student.objects.seniors(): # won't work -django reconstructs the model from migrations
    #     student.metoda_mea()

def backwards(apps, models):
    print("Nu putem pune datele inapoi")

class Migration(migrations.Migration):

    dependencies = [
        ('curs', '0010_alter_student_unique_together'),
    ]

    operations = [
        migrations.RunPython(forward, backwards)
    ]
